package org.twelve.llmgateway.contract;

public enum GatewayErrorCode {
    UNAUTHENTICATED,
    DELEGATION_FORBIDDEN,
    INVALID_REQUEST,
    RATE_LIMITED,
    AGENT_LOOP_LIMIT_REACHED,
    AGENT_LOOP_SCOPE_REQUIRED,
    AGENT_LOOP_GUARD_UNAVAILABLE,
    PROVIDER_UNAVAILABLE,
    USAGE_RECONCILIATION_REQUIRED,
    INTERNAL_ERROR
}
