package org.example.billing.contract;

public enum BillingErrorCode {
    INVALID_REQUEST,
    UNAUTHENTICATED,
    FORBIDDEN,
    SERVICE_CREDENTIAL_INVALID,
    BILLING_ASSERTION_INVALID,
    BILLING_UNAVAILABLE,
    DECISION_NOT_FOUND,
    DECISION_EXPIRED,
    DECISION_MISMATCH,
    INSUFFICIENT_CREDIT,
    PRICING_RULE_MISSING,
    USAGE_UNKNOWN,
    RECONCILIATION_REQUIRED,
    IDEMPOTENCY_CONFLICT,
    INTERNAL_ERROR
}
